CREATE TABLE [Recipes].[Recipe](
	[Id] INT IDENTITY(10000,1) NOT NULL,
	[Name] [NVARCHAR](512) NOT NULL,
	[Description] [NVARCHAR](MAX) NOT NULL,
	[AuthorId] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] [DATETIME2](7) NOT NULL DEFAULT SYSDATETIME(),
	[UpdatedDate] [DATETIME2](7) NOT NULL DEFAULT SYSDATETIME(),
	[DeletedDate] [DATETIME2](7) NULL,
 CONSTRAINT [PK_RecipesRecipe] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]