CREATE TABLE [Recipes].[Group](
	[Id] INT IDENTITY(100000,1) NOT NULL,
	[ParentId] INT NULL,
	[Name] [NVARCHAR](512) NOT NULL,
	[CreatedDate] [DATETIME2](7) NOT NULL DEFAULT SYSDATETIME(),
	[UpdatedDate] [DATETIME2](7) NOT NULL DEFAULT SYSDATETIME(),
 CONSTRAINT [PK_RecipesGroup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]